# @prettier
on: push

name: 'Test Find Issue Key'

jobs:
  test-find-issue-key:
    name: 'Find Issue Key'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: "gajira-find-issue-key"

      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL || secrets.JIRA_EMAIL}}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN || secrets.JIRA_TOKEN}}

      - name: 'Find Issue Key'
        id: find
        uses: ./
        with:
          github-token: ${{github.token}}
          string: DVPS-335 | will search in branch name

      - name: 'Find issue info'
        env:
          ISSUE_FOUND: ${{ steps.find.outputs.issue }}
        run: |
          if [ "${ISSUE_FOUND}" == "DVPS-335" ];then
            echo "::info:: Issue ${ISSUE_FOUND} was found"
          else
            echo "::error:: Find issue from string failed"
          fi
