name: Review - Check for code issues
on:
  pull_request:
    types: [labeled, opened, synchronize, reopened, edited]
    paths: ['src/**/*.ts']
jobs:
  eslint:
    name: runner / eslint
    permissions: write-all
    strategy:
      matrix:
        directory: ['./']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v3.3.0
        with:
          node-version: '16'
          cache: 'yarn'

      - uses: bitflight-devops/shell-scripts@v2.2
        name: Install shell utility scripts

      - name: get email
        shell: bash
        run: |
          git config --global user.email $(get_last_github_author_email 'wearsafe.jenkins@gmail.com')
          git config --global user.name $(get_last_github_author_name)

      - name: Install Packages
        continue-on-error: true
        run: |
          yarn install

      - name: eslint fix
        working-directory: ${{ matrix.directory }}
        if: contains(github.event.pull_request.labels.*.name, 'autolint')
        id: fix
        continue-on-error: true
        run: |
          yarn run lint

      - name: Commit Fixes
        working-directory: ${{ matrix.directory }}
        if: contains(github.event.pull_request.labels.*.name, 'autolint')
        continue-on-error: true
        run: |
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "Auto-fixed linting errors - remember to run 'yarn run lint:ts' before committing"
            git push
          fi

      - name: Lint Base
        uses: reviewdog/action-eslint@v1
        with:
          filter_mode: diff_context
          reporter: github-pr-review
          eslint_flags: '--ext .js,.ts -c ${{ matrix.directory }}/.eslintrc.cjs ${{ matrix.directory }}'
